---
title: "Introduction to the USgas package"
author: '@Rami_Krispin'
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Happy to announce that the [USgas](https://ramikrispin.github.io/USgas/) package is now on CRAN. The package provides an overview of natural gas demand in the US in a time-series format (state and aggregate levels). That includes  more than 100 series, monthly and year, in the following datasets:

* `us_total` - The US annual natural gas consumption by state-level between 1997 and 2019, and aggregate level between 1949 and 2019
* `us_monthly` - The monthly demand for natural gas in the US between 2001 and 2020
* `us_residential` - The US monthly natural gas residential consumption by state and aggregate level between 1989 and 2020

This package is a mirror of the [USgrid](https://github.com/RamiKrispin/USgrid) package that focuses on electricity demand (and supply) in the US. Additional information available:

* Source code - https://github.com/RamiKrispin/USgas
* Package site - https://ramikrispin.github.io/USgas/
* Data source - US Energy Information Administration, https://www.eia.gov/